#docker build -t vulkan-sdk:1.4.328.1 --build-arg VULKAN_SDK_VERSION=1.4.328.1 -f ./Dockerfile.lunarg .
FROM debian:trixie-slim

# Metadata
LABEL maintainer="pattakosn@fastmail.com" \
      description="debian vulkan build environment" \
      debian.version="trixie"

ARG VULKAN_SDK_VERSION=1.4.328.1
ENV DEBIAN_FRONTEND=noninteractive TZ=Europe/Paris

RUN  apt-get update \
  && apt-get install -y --no-install-recommends \
     bash vim wget ca-certificates xz-utils \
     libglm-dev cmake libxcb-dri3-0 libxcb-present0 libpciaccess0 \
     libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev libx11-dev g++ gcc clang \
     libwayland-dev libxrandr-dev libxcb-randr0-dev libxcb-ewmh-dev \
     git python-is-python3 bison libx11-xcb-dev liblz4-dev libzstd-dev \
     ocaml-core ninja-build pkg-config libxml2-dev wayland-protocols python3-jsonschema \
     clang-format qtbase5-dev qt6-base-dev make ninja-build

RUN mkdir -p /app \
 && cd /app \
 && wget https://sdk.lunarg.com/sdk/download/${VULKAN_SDK_VERSION}/linux/vulkansdk-linux-x86_64-${VULKAN_SDK_VERSION}.tar.xz \
 && tar -xJf vulkansdk-linux-x86_64-${VULKAN_SDK_VERSION}.tar.xz -C /app \
 #&& cd /app/${VULKAN_SDK_VERSION} \
 #&& /app/${VULKAN_SDK_VERSION}/vulkansdk -j 20 all \
 && mv /app/${VULKAN_SDK_VERSION}/x86_64 /app/sdk \
 && rm -rf /app/vulkansdk-linux-x86_64-${VULKAN_SDK_VERSION}.tar.xz /app/${VULKAN_SDK_VERSION} \
 && apt-get purge -y wget ca-certificates xz-utils qtbase5-dev qt6-base-dev \
 && apt-get autoremove -y \
 && rm -rf /var/lib/apt/lists/*
#RUN bash -c '\
#  set -e; \
#  SDK_DIR=/app/1.4.328.1/x86_64; \
#  BEFORE=$(mktemp); AFTER=$(mktemp); \
#  env -i bash -c "set -o posix; set | sort" > "$BEFORE"; \
#  env -i bash -c ". $SDK_DIR/setup-env.sh >/dev/null 2>&1; set -o posix; set | sort" > "$AFTER"; \
#  echo "### Vulkan SDK environment variables:"; \
#  diff "$BEFORE" "$AFTER" | grep "^>" | sed "s/^> //" | while IFS== read -r key val; do \
#    echo "ENV $key=$val"; \
#  done > /tmp/envs.Dockerfile; \
#  cat /tmp/envs.Dockerfile; \
#  '
#RUN bash -c 'cat /tmp/envs.Dockerfile >> /root/final_envs.Dockerfile && cat /root/final_envs.Dockerfile'
ENV VULKAN_SDK=/app/sdk
ENV PATH=${VULKAN_SDK}/bin:$PATH
ENV LD_LIBRARY_PATH=${VULKAN_SDK}/lib:$LD_LIBRARY_PATH
ENV VK_ICD_FILENAMES=${VULKAN_SDK}/etc/vulkan/icd.d
ENV VK_LAYER_PATH=${VULKAN_SDK}/etc/vulkan/explicit_layer.d
RUN groupadd --gid $USER_GID $USERNAME || true \
 && useradd --uid $USER_UID --gid $USER_GID -m -s /bin/bash $USERNAME \
 && apt-get update && apt-get install -y sudo \
 && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
 && chmod 0440 /etc/sudoers.d/$USERNAME
#WORKDIR /home/vscode
CMD ["/bin/bash"]